testfoo: testfoo123
db-config:
  spring:
    jpa:
      pro1: value1
      pro2: value2
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.181:8761/eureka/
server:
  port: 8762  
  
spring:
  application:
    name: service-hi
  sleuth:
    feign:
      enabled: true
  zipkin:
    baseUrl: http://192.168.3.181:9411/
    sender:
      type: web
feign:
  hystrix:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,httptrace,logfile